### ISSUE TITLE
gimp 3.0 Support

### ISSUE THREAD

**Issue by sambhavsaggi** [bootchk/resynthesizer#96] opened 2021-05-30 18:30 UTC
Add support for gimp devel (2.99) packages

**Comment by bootchk** [comment] 2021-05-30 19:41
Duplicate of #67

Please read the readme about the "deprecations" branch.  I have tested it with 2.99 but it is not for general public consumption.

**Closed by bootchk** 2021-05-30 19:41 UTC

**Comment by Neustradamus** [comment] 2025-05-22 12:03
@bootchk: Thanks!

Tag:
- https://github.com/bootchk/resynthesizer/releases/tag/v3.0

Release:
- https://github.com/bootchk/resynthesizer/releases/tag/v3.0

Linked to:
- https://github.com/bootchk/resynthesizer/issues/153
- https://github.com/bootchk/resynthesizer/issues/96
- https://github.com/bootchk/resynthesizer/issues/67
